version: "3.9"

services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      - my-network
  kafka:
    image: wurstmeister/kafka:2.11-1.1.0
    links:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "topic-actors:1:1,actors-response:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - my-network
  mongodb:
    image: mongo:4
    ports:
      - 27017:27017
    environment:
      - MONGO_URL=mongodb://mongodb:27017
    networks:
      - my-network
  api:
    image: my-api
    links:
      - mongodb
    build: api/
    ports: 
      - "3001:3001"
    networks:
      - my-network
  actors:
    image: my-actors
    links:
      - mongodb
      - app
    build: actors/
    ports: 
      - "3002:3002"
    networks:
      - my-network

networks:
  my-network: